apiVersion: v1
kind: Pod
metadata:
  name: payment-api
spec:
  containers:
    - name: payment
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Starting payment API"
          echo "Connecting to payment database"
          exit 1
