apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs

spec:
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend-v2

    spec:
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
