apiVersion: v1
kind: Pod
metadata:
  name: report-api
spec:
  nodeSelector:
    workload: reporting
  containers:
    - name: report
      image: nginx:latest
      ports:
        - containerPort: 80
