apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api

spec:
  replicas: 4

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      labels:
        app: catalog

    spec:
      containers:
        - name: catalog
          image: nginx:latest

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
